      SUBROUTINE D01FCF(NDIM,A,B,MINPTS,MAXPTS,FUNCTN,EPS,ACC,LENWRK,
     *                  WRKSTR,FINVAL,IFAIL)
C     MARK 13 REVISED. USE OF MARK 12 X02 FUNCTIONS (APR 1988).
C
C     ADAPTIVE MULTIDIMENSIONAL INTEGRATION SUBROUTINE
C

      STOP "This routine requires D01FCF from the NAG libary"
      RETURN
      END

